[tool.poetry]
name = "testrunner"
version = "0.1.0"
description = ""
authors = ["ziegnes <ziegnes@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
pydantic = "^2.4.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
